name: CI/CD Pipeline with MongoDB (Automated with Python)

on:
  push:
    branches:
      - main

jobs:
  connect-mongodb:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8  # Or your preferred Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo

      # Run the Python script
      - name: Connect to MongoDB and list collections
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # MongoDB URI stored as a secret
          DB_NAME: sampleupload  # Set your database name
        run: python connect_mongo.py
